### ISSUE TITLE
FE - nazvy

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/cloud-service#5]
Z tychto nazvov moc nepoznat aky je rozdiel medzi file a selectedFile

https://github.com/AppsLab-2/cloud-service/blob/d256eb654fcaba92136bb1ece28a3d18b3b9b816/frontend/src/app/components/home-page/home-page.component.ts#L13

**Comment by MatejMeciak** [comment]
Tá file premenná bola zbytočná.
